# Generated by Django 2.0.5 on 2018-08-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='notetag',
        ),
        migrations.AddField(
            model_name='notes',
            name='notetag',
            field=models.ForeignKey(default=1, on_delete='CASCADE', to='repository.NoteTag', verbose_name='笔记标签'),
            preserve_default=False,
        ),
    ]
