# Generated by Django 2.0.5 on 2018-08-09 16:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20180809_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文'),
        ),
    ]
