# Generated by Django 2.0.5 on 2018-08-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20180810_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='summary',
            field=models.CharField(max_length=255, null=True, verbose_name='简介'),
        ),
    ]
