# Generated by Django 2.0.5 on 2018-08-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_userfans_follow_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='usertag',
        ),
        migrations.DeleteModel(
            name='UserTag',
        ),
    ]
