# Generated by Django 2.0.5 on 2018-08-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20180813_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('relationship_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
            ],
        ),
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('groupid', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=128, verbose_name='小组组名')),
                ('introduction', models.CharField(max_length=255, null=True, verbose_name='小组简介')),
                ('public_notice', models.TextField(verbose_name='小组公告')),
                ('member_count', models.IntegerField(default=1, verbose_name='组员数量')),
                ('member_limit', models.IntegerField(default=50, verbose_name='组员上限')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTag',
            fields=[
                ('grouptag_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('grouptag_name', models.CharField(max_length=32, verbose_name='小组标签')),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=32, verbose_name='请求状态')),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('request_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_name', models.CharField(max_length=32, verbose_name='请求类型')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='activities_count',
            field=models.IntegerField(default=0, verbose_name='参加活动数量'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='groups_count',
            field=models.IntegerField(default=0, verbose_name='小组数量'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='history_activities_count',
            field=models.IntegerField(default=0, verbose_name='历史参加活动数量'),
        ),
        migrations.AddField(
            model_name='groups',
            name='group_owner',
            field=models.ForeignKey(on_delete='CASCADE', to='repository.UserInfo', verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='groups',
            name='grouptag',
            field=models.ForeignKey(on_delete='CASCADE', to='repository.GroupTag', verbose_name='小组标签'),
        ),
        migrations.AddField(
            model_name='grouprequest',
            name='initiator',
            field=models.ForeignKey(on_delete='CASCADE', related_name='applicant', to='repository.UserInfo', verbose_name='发起人'),
        ),
        migrations.AddField(
            model_name='grouprequest',
            name='request_status',
            field=models.ForeignKey(on_delete='CASCADE', to='repository.RequestStatus', verbose_name='请求状态'),
        ),
        migrations.AddField(
            model_name='grouprequest',
            name='request_type',
            field=models.ForeignKey(on_delete='CASCADE', to='repository.RequestType', verbose_name='请求类型'),
        ),
        migrations.AddField(
            model_name='grouprequest',
            name='target_group',
            field=models.ForeignKey(on_delete='CASCADE', to='repository.Groups', verbose_name='目标小组'),
        ),
        migrations.AddField(
            model_name='grouprequest',
            name='target_user',
            field=models.ForeignKey(on_delete='CASCADE', related_name='target', to='repository.UserInfo', verbose_name='对象'),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='group',
            field=models.ForeignKey(on_delete='CASCADE', to='repository.Groups', verbose_name='小组'),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='member',
            field=models.ForeignKey(on_delete='CASCADE', to='repository.UserInfo', verbose_name='成员'),
        ),
    ]
