# Generated by Django 2.0.5 on 2018-08-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_auto_20180813_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='public_notice',
            field=models.TextField(null=True, verbose_name='小组公告'),
        ),
    ]
