# Generated by Django 2.0.5 on 2018-08-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20180813_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='activities_count',
            field=models.IntegerField(default=0, verbose_name='小组活动数量'),
        ),
        migrations.AddField(
            model_name='groups',
            name='history_activities_count',
            field=models.IntegerField(default=0, verbose_name='小组历史活动数量'),
        ),
    ]
