# Generated by Django 2.0.5 on 2018-08-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_auto_20180813_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activity_request', models.TextField(verbose_name='活动内容')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('sign_count', models.IntegerField(default=0, verbose_name='打卡数量')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySign',
            fields=[
                ('sign_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='打卡内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='打卡时间')),
                ('activity', models.ForeignKey(on_delete='CASCADE', to='repository.Activities', verbose_name='活动')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityStatus',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=32, verbose_name='活动状态')),
            ],
        ),
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('notice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, verbose_name='通知内容')),
                ('notice_time', models.DateTimeField(auto_now_add=True, verbose_name='通知时间')),
            ],
        ),
        migrations.CreateModel(
            name='NoticeStatus',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=32, verbose_name='通知状态')),
            ],
        ),
        migrations.RemoveField(
            model_name='groups',
            name='history_activities_count',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='public_notice',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='activities_count',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='history_activities_count',
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='获得积分'),
        ),
        migrations.AddField(
            model_name='groups',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='小组积分'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='activities_count',
            field=models.IntegerField(default=1, verbose_name='历史小组活动数量'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(max_length=32, verbose_name='小组组名'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='introduction',
            field=models.CharField(max_length=128, null=True, verbose_name='小组简介'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='summary',
            field=models.CharField(max_length=128, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(max_length=64, verbose_name='标题'),
        ),
        migrations.AddField(
            model_name='notices',
            name='status',
            field=models.ForeignKey(on_delete='CASCADE', to='repository.NoticeStatus', verbose_name='通知状态'),
        ),
        migrations.AddField(
            model_name='notices',
            name='to_user',
            field=models.ForeignKey(on_delete='CASCADE', to='repository.UserInfo', verbose_name='接收者'),
        ),
        migrations.AddField(
            model_name='activitysign',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', to='repository.UserInfo', verbose_name='打卡人'),
        ),
        migrations.AddField(
            model_name='activities',
            name='group',
            field=models.ForeignKey(on_delete='CASCADE', to='repository.Groups', verbose_name='所属小组'),
        ),
        migrations.AddField(
            model_name='activities',
            name='status',
            field=models.ForeignKey(on_delete='CASCADE', to='repository.ActivityStatus', verbose_name='活动状态'),
        ),
    ]
