# Generated by Django 2.0.5 on 2018-08-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_auto_20180814_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfans',
            name='is_special',
        ),
    ]
