# Generated by Django 2.0.5 on 2018-08-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_activities_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberIdentity',
            fields=[
                ('identity_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identity_name', models.CharField(max_length=32, verbose_name='身份')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupmembers',
            name='relationship_id',
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='group',
            field=models.ForeignKey(on_delete='CASCADE', primary_key=True, serialize=False, to='repository.Groups', verbose_name='小组'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='member',
            field=models.ForeignKey(on_delete='CASCADE', primary_key=True, to='repository.UserInfo', verbose_name='成员'),
        ),
    ]
