# Generated by Django 2.0.5 on 2018-08-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_auto_20180818_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembers',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmembers',
            name='member',
        ),
        migrations.DeleteModel(
            name='GroupMembers',
        ),
    ]
