# Generated by Django 2.0.5 on 2018-08-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_auto_20180819_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouprequest',
            name='target_group',
            field=models.CharField(max_length=32, verbose_name='目标小组'),
        ),
    ]
