# Generated by Django 2.0.5 on 2018-08-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0019_auto_20180819_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开始时间'),
        ),
    ]
