# Generated by Django 2.0.5 on 2018-08-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0020_auto_20180819_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='start_time',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
    ]
